from .announcements import announcementsRouter
from .assignments import assignmentsRouter
from .divisions import divisionsRouter
from .excuses import excusesRouter
from .feedback import feedbacksRouter
from .meetings import meetingsRouter
from .roles import rolesRouter
from .submissions import submissionsRouter
from .users import usersRouter
