from enum import Enum


class AnnouncementsCategory(str, Enum):
    INTERNSHIP = "internship"
    EVENT = "event"
    WORKSHOP = "workshop"
    COMPETITION = "competition"
    OTHER = "other"


class CorePermissions(int, Enum):
    UPDATE_USER = 1
    DELETE_USER = 2
    CREATE_DIVISION = 4
    UPDATE_DIVISION = 8
    DELETE_DIVISION = 16
    CREATE_ROLE = 32
    UPDATE_ROLE = 64
    DELETE_ROLE = 128


class FeaturePermissions(int, Enum):
    CREATE_ASSIGNMENT = 1
    UPDATE_ASSIGNMENT = 2
    DELETE_ASSIGNMENT = 4
    CREATE_ANNOUNCEMENT = 8
    UPDATE_ANNOUNCEMENT = 16
    DELETE_ANNOUNCEMENT = 32
    CREATE_MEETING = 64
    UPDATE_MEETING = 128
    DELETE_MEETING = 256
    CREATE_SUBMISSION = 512
    UPDATE_SUBMISSION = 1024
    DELETE_SUBMISSION = 2048
    CREATE_EXCUSE = 4096
    UPDATE_EXCUSE = 8192
    DELETE_EXCUSE = 16384
    CREATE_FEEDBACK = 32768
    UPDATE_FEEDBACK = 65536
    DELETE_FEEDBACK = 131072
